---

- name: download and unzip node exporter 
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    dest: /home 
    remote_src: yes
    