---
- name: Install default Apache Web Server
  hosts: staging_web
  become: yes

  tasks:
  - name: LINUX version 
    debug: var=ansible_os_family 


  - block:   #     ======block for REDHAT=======
    - name: Install Apache WebServer for RedHat
      yum: name=httpd state=latest 
     
      
    - name: Start Web service RedHat
      service: name=httpd state=started enabled=yes
   
    when: ansible_os_family == "RedHat"

  - block:   #     ======block for Debian=======
    - name: Install Apache WebServer for Debian
      apt: name=apache2 state=latest

    - name:  Start Web service Debian
      service: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"

  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted 
    when: ansible_os_family == "RedHat"

  - name: Restart Apache Debian
    service: name=apache2 state=restarted 
    when: ansible_os_family == "Debian"