---
- name: Install default Apache Web Server
  hosts: staging_web
  become: yes

  tasks:
  - name: Install Apache WebServer
    apt: name-httpd state=latest 
      
  - name: Start Apache and Enable it on the every boot
    service: name=httpd state-started enable=yes
