---
- name: Delegate
  hosts: staging_APP
  become: yes

  vars:
   mytext: " Obnovlenie"

  tasks:
  - name: Ping test
    ping:

  #- name: Unregister Server from Load Balanser 
    #shell: echo This server {{ invenory_hostname }} was deregistered from our Load Balancer, node name is {{ ansible_nodename }} >> /home/log.txt
    #delegate_to: 127.0.01 


  - name: Create file
    copy:
      dest: /home/file1.txt
      content: |
           This is File1
           On ENGLISH new system 
           On Russia {{ mytext }}
    delegate_to: linux_server4   ### чтобы запускать на 1 из серверов 

  - name: Create file
    copy:
      dest: /home/file2.txt
      content: |
           This is File2
           On ENGLISH new system 
           On Russia {{ mytext }}       

  - name: Update my Database
    shell:  echo UPDATING Database.....
    run_once: true  ### Идёт по списку серверов обновляет 1 раз 

  - name: Reboot my servers
    shell: sleep 3 && reboot now
    async: 1 #таймаут сколько надо ждать
    poll: 0  ## сколько надо ждать 

  - name: Wait till my servers will come up online 
    wait_for:
        host: staging_servers
        state: started
        delay: 5   ### ждём через 5 сек
        timeout: 40 ### максимум ждём 40 сек
    ###delegate_to: 192.168.240.147   если ждать на какой-либо главной машине 
